spring:
  datasource:
    url: jdbc:h2:mem:test_mem
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  aop:
    proxy-target-class: false

